version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - $API_LOCAL_PORT:$API_DOCKER_PORT
    environment:
      - API_PORT=$API_DOCKER_PORT
      - DATABASE_URL=$DATABASE_URL
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
      - JWT_SECRET=$JWT_SECRET
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VUE_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - $UI_LOCAL_PORT:$UI_DOCKER_PORT
    volumes:
      - ./frontend:/app

  postgres:
    image: postgres
    ports:
      - $POSTGRESQL_LOCAL_PORT:$POSTGRESQL_DOCKER_PORT
    environment:
      POSTGRES_USER: $POSTGRESQL_USER
      POSTGRES_PASSWORD: $POSTGRESQL_PASSWORD
      POSTGRES_DB: $POSTGRESQL_DATABASE
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U comigotech"]
      interval: 2s
      timeout: 1s
      retries: 20

  prisma_preview:
    build:
      context: ./backend
      dockerfile: ../scripts/prisma.dockerfile
    ports:
      - "5555:5555"
    depends_on:
      postgres:
        condition: service_healthy
